### ISSUE TITLE
low-pixel image handling

### ISSUE THREAD

**Issue by dexhunter** [lllyasviel/sketchKeras#2]
I tried this method and here are my results:

## Original
![000000](https://user-images.githubusercontent.com/6930518/27008759-0c117ef6-4eae-11e7-905f-e96d8f9a5d4d.jpg)

## After "sketched"
![sketchkeras](https://user-images.githubusercontent.com/6930518/27008783-cc323892-4eae-11e7-9b34-362dc009669f.jpg)
![sketchkeras_pured](https://user-images.githubusercontent.com/6930518/27008784-cc33a84e-4eae-11e7-984f-bea3a2dc253b.jpg)
![sketchkeras_enhanced](https://user-images.githubusercontent.com/6930518/27008786-cc36c88a-4eae-11e7-9708-9006ce2d31dc.jpg)
![sketchkeras_colored](https://user-images.githubusercontent.com/6930518/27008785-cc36883e-4eae-11e7-8e74-9d0d568d4218.jpg)

Can you give a hint on what's your training sets look like? Thank you.

**Comment by lllyasviel** [comment]
The training set is about 1400 real pair of human paintings and human sketch, by 5 artists.
