### ISSUE TITLE
why input shape is (None, 512, 512, 1)?

### ISSUE THREAD

**Issue by youkaichao** [lllyasviel/sketchKeras#3]
I load the mod and print mod.InputLayers[0].input_shape and get the  (None, 512, 512, 1). 
But the code in main.py indicates that the input shape should be [None, 512, 512, 3] or [3, 512, 512, None] depending on the data format. 
When I feed [3, 512, 512, batch_size] or [batch_size, 512, 512, 3] to mod.predict, Exception is raised. 
Can you help me ? What's going on here?

**Comment by lllyasviel** [comment]
has been checked in group.
