### ISSUE TITLE
Actual program which describes the structure of neural u-net?

### ISSUE THREAD

**Issue by bondeanikets** [lllyasviel/sketchKeras#5]
There is no code in this repository that deals with creation of creating a neural net in tensorflow. Could you please upload it? Your results seem interesting.

**Comment by abbychau** [comment]
The keras models can be visualized. 

base_generator:
![base_generator](https://user-images.githubusercontent.com/350283/31585683-ab801c38-b1f8-11e7-9b09-4b1ab9d4266c.png)


style2paints:
![style2paints](https://user-images.githubusercontent.com/350283/31585684-aba9cd26-b1f8-11e7-875c-fbb581ab00bd.png)


u can use tensorboard as well.

**Comment by bondeanikets** [comment]
Thanks!

**Comment by FantasyJXF** [comment]
@abbychau  So it looks like that this `sketchKeras` model is just like U net, and treat the sketch extract as a edge pixel classificate job?
